/**
 * Auto-generated by Payload CMS — run `pnpm payload generate:types` to regenerate.
 * This is a placeholder file. Real types will be generated from the Payload config.
 */

export interface Page {
  id: string
  title: string
  slug: string
  status: 'draft' | 'published'
  hero?: {
    heading?: string
    subheading?: string
    backgroundImage?: Media
    ctaLabel?: string
    ctaHref?: string
    variant?: 'fullscreen' | 'compact' | 'split'
  }
  sections?: Block[]
  meta?: SEOMeta
  createdAt: string
  updatedAt: string
}

export interface Project {
  id: string
  title: string
  slug: string
  coverImage: Media
  gallery?: { image: Media; caption?: string }[]
  description?: unknown
  location?: string
  country?: string
  year?: number
  areaSqm?: number
  houseType?: 'single-storey' | 'two-storey' | 'module' | 'custom'
  featured?: boolean
  publishedAt?: string
  meta?: SEOMeta
  createdAt: string
  updatedAt: string
}

export interface News {
  id: string
  title: string
  slug: string
  coverImage?: Media
  excerpt?: string
  content: unknown
  author?: string
  publishedAt: string
  tags?: { tag: string }[]
  status: 'draft' | 'published'
  meta?: SEOMeta
  createdAt: string
  updatedAt: string
}

export interface Gallery {
  id: string
  title: string
  slug: string
  coverImage?: Media
  images?: { image: Media; caption?: string }[]
  category?: 'exterior' | 'interior' | 'production' | 'process'
  order?: number
  createdAt: string
  updatedAt: string
}

export interface Navigation {
  id: string
  locale: 'en' | 'lv' | 'de' | 'it'
  items: NavItem[]
}

export interface NavItem {
  label: string
  href: string
  children?: { label: string; href: string }[]
}

export interface Media {
  id: string
  url: string
  filename: string
  mimeType: string
  width?: number
  height?: number
  alt: string
  caption?: string
  credit?: string
  sizes?: {
    thumbnail?: ImageSize
    card?: ImageSize
    hero?: ImageSize
    square?: ImageSize
  }
}

export interface ImageSize {
  url: string
  width: number
  height: number
}

export interface SEOMeta {
  title?: string
  description?: string
  image?: Media
}

export interface SiteSettings {
  companyName?: string
  tagline?: string
  phone?: string
  email?: string
  address?: string
  vatNumber?: string
  socialLinks?: {
    facebook?: string
    instagram?: string
    linkedin?: string
    youtube?: string
  }
  footerText?: unknown
  defaultOgImage?: Media
  googleAnalyticsId?: string
  plausibleDomain?: string
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Block = Record<string, any> & { blockType: string }

export interface PaginatedDocs<T> {
  docs: T[]
  totalDocs: number
  totalPages: number
  page: number
  limit: number
  hasNextPage: boolean
  hasPrevPage: boolean
}
